// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
	"github.com/sankethkini/ConcurrencyInGo/application"
	"github.com/sankethkini/ConcurrencyInGo/db"
)

// Injectors from wire.go:

func IntializeApp() *application.MyApp {
	iClinet := _wireClientValue
	myApp := application.NewApp(iClinet)
	return myApp
}

var (
	_wireClientValue = db.NewClient()
)

// wire.go:

var appSet = wire.NewSet(wire.InterfaceValue(new(db.IClinet), db.NewClient()), application.NewApp)
