// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/google/wire"
	"github.com/sankethkini/ConcurrencyInGo/application"
	"github.com/sankethkini/ConcurrencyInGo/config"
	"github.com/sankethkini/ConcurrencyInGo/db"
)

// Injectors from wire.go:

func IntializeApp() *application.MyApp {
	dbHelper := _wireClientValue
	appConfig := config.LoadConfig()
	itaxRates := config.NewRates(appConfig)
	myApp := application.NewApp(dbHelper, itaxRates)
	return myApp
}

var (
	_wireClientValue = db.NewClient()
)

// wire.go:

var appSet = wire.NewSet(wire.InterfaceValue(new(db.DBHelper), db.NewClient()), config.LoadConfig, config.NewRates, application.NewApp)
